#pragma once
#include "RPC.h"

// State tracking
enum RobotState {
  NO_WALL,
  FOLLOWING_LEFT,
  FOLLOWING_RIGHT,
  FOLLOWING_CENTER,
  TOO_CLOSE,
  TOO_FAR,
  CLOSE_TO_RIGHT,
  CLOSE_TO_LEFT,
  TURNING_CORNER,
  RANDOM_WANDER,
  INSIDE_CORNER,
  OUTSIDE_CORNER,
  COLLIDE_BEHAVIOR,
  RUNAWAY_BEHAVIOR,
  FOLLOW_BEHAVIOR,
  INSIDE_DEADBAND,
  STOP,
  MOVE_FORWARD,
  TURN_LEFT,
  TURN_RIGHT,
  MOVE_BACKWARD,
  SLAM_BEHAVIOR,
  MATRIX_PATH_PLANNING,
  GRID_LOCALIZATION,
};

enum SLAMState{
  DETECT_OBSTACLE,
  EXPLORE_START,
  EXPLORING,
  UPDATE_MAP,
};

extern RobotState currentState;
extern SLAMState currentSLAMState;